server: 
  port: 9001
#spring: 
#  datasource: 
#    ddl-auto: create-drop
#    driver-class-name: org.postgresql.Driver
#    driverClassName: org.postgresql.Driver
#    password: sarahfred131216
#    platform: postgresql
#    url: "jdbc:postgresql://localhost:5432/"
#    username: postgres
#    profile: prod
spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://192.168.0.18:3306/storyline
        username: app 
        password: sarahfred
        driver-class-name: com.mysql.jdbc.Driver  